DO $$
BEGIN
  EXECUTE 'REVOKE ALL ON FUNCTION public.create_invoice_atomic(UUID, TEXT, TEXT, TEXT, JSONB, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, DATE, DATE, INTEGER) FROM PUBLIC';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.create_invoice_atomic(UUID, TEXT, TEXT, TEXT, JSONB, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, DATE, DATE, INTEGER) TO authenticated';
END;
$$;
